### ISSUE TITLE
Building is getting stuck waiting for IO

### ISSUE THREAD

**Issue by joamag** [MatteoH2O1999/setup-python#16]
## Description

I believe there's an issue with the apt dependency installation that is making the job wait for input.

Here's a screenshot of the problem:

![image](https://github.com/MatteoH2O1999/setup-python/assets/25441/7c67c92d-ba07-469e-bf58-739e8e7caad7)

**Comment by joamag** [comment]
cc @MatteoH2O1999

**Comment by MatteoH2O1999** [comment]
As you can see [here](https://github.com/MatteoH2O1999/setup-python/actions/runs/5367028286) this is not usual behavior, I'm afraid you'll have to give me something more than a screenshot to work with:
* What runner are you using?
* What version of Python are you trying to install?
* Can you give me a link to the failed run?

**Comment by joamag** [comment]
Sorry, it's a private repo so I can't share the URL to the failing job.
It's running with on self-hosted runner, this is probably the reason behind the different behavior.

**Comment by MatteoH2O1999** [comment]
If you're running on self-hosted then i fail to see why you would use my action. The benefit of self-hosted is that you get to define your own toolcache. If you want to have, say, Python 3.2.3, you would simply install it into the runner toolcache and [actions/setup-python](https://github.com/actions/setup-python) will detect it even if it does not support installing it anymore.
My action is useful in the Github-hosted case as every time you request a runner a fresh VM is created for you, so you cannot define your own toolcache.
In any case, if you still want to use this action, I'll still need to see at the very least the logs of the failed run, even as a raw text, otherwise I'm literally shooting in the dark.

**Comment by joamag** [comment]
I would love to use your action as it would simplify the setup of python 2.7.
I'll try to provide the log.

**Comment by joamag** [comment]
Here they are 

[logs_397.zip](https://github.com/MatteoH2O1999/setup-python/files/11867302/logs_397.zip)

**Comment by joamag** [comment]
Here they are:
[Build Hosted (2.7).zip](https://github.com/MatteoH2O1999/setup-python/files/11867315/Build.Hosted.2.7.zip)

**Comment by MatteoH2O1999** [comment]
[build-and-install-python/167](https://github.com/MatteoH2O1999/build-and-install-python/pull/167) should fix this issue.
As soon as 2.7 compiles on Windows I'll make a new release

**Comment by MatteoH2O1999** [comment]
Closing this as fixed with version [v1.4.0](https://github.com/MatteoH2O1999/setup-python/releases/tag/v1.4.0). Feel free to reopen if the problem persists
